Update projects.yaml
Add additional policy to projects namespace to avoid issue with 403 lack of permissions to create IAMPartialPolicy:

ERROR: [kpt] 1 resource failed to apply:
- "kcc-jcwc-bp-dev-owners-permissions" (IAMPartialPolicy) failed:
    "Update call failed: error fetching live state for resource: error reading underlying resource: summary: Error when reading or editing Resource "project \"jcwc-bp-dev\"" with IAM Policy: Error retrieving IAM policy for project "jcwc-bp-dev": googleapi: Error 403: The caller does not have permission, forbidden"